### ISSUE TITLE
Win 10 1903 + python 3.6.5

### ISSUE THREAD

**Issue by andydis** [4n4nk3/Wordlister#15]
`  slice_and_run(my_iterator)
  File "C:\Users\manager\Downloads\Wordlister-master\Wordlister-master\wordlister.py", line 86, in slice_and_run
    with Pool(args.cores) as pool:
  File "C:\Users\manager\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\manager\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\pool.py", line 174, in __init__
    self._repopulate_pool()
  File "C:\Users\manager\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\pool.py", line 239, in _repopulate_pool
    w.start()
  File "C:\Users\manager\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\manager\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\manager\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\manager\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\manager\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\manager\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\manager\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\manager\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\manager\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\manager\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\manager\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\manager\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\manager\Downloads\Wordlister-master\Wordlister-master\wordlister.py", line 210, in <module>
    real_run()
  File "C:\Users\manager\Downloads\Wordlister-master\Wordlister-master\wordlister.py", line 199, in real_run
    slice_and_run(my_iterator)
  File "C:\Users\manager\Downloads\Wordlister-master\Wordlister-master\wordlister.py", line 86, in slice_and_run
    with Pool(args.cores) as pool:
  File "C:\Users\manager\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\manager\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\pool.py", line 174, in __init__
    self._repopulate_pool()
Traceback (most recent call last):
  File "C:\Users\manager\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\pool.py", line 239, in _repopulate_pool
  File "<string>", line 1, in <module>
  File "C:\Users\manager\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\spawn.py", line 105, in spawn_main
    w.start()
  File "C:\Users\manager\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\process.py", line 105, in start
    exitcode = _main(fd)
  File "C:\Users\manager\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\spawn.py", line 114, in _main
    self._popen = self._Popen(self)
  File "C:\Users\manager\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\context.py", line 322, in _Popen
    prepare(preparation_data)
  File "C:\Users\manager\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\spawn.py", line 225, in prepare
    return Popen(process_obj)
  File "C:\Users\manager\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\manager\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\manager\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
    run_name="__mp_main__")
  File "C:\Users\manager\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
  File "C:\Users\manager\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 263, in run_path
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    pkg_name=pkg_name, script_name=fname)`

**Comment by tomventa** [comment]
Look at the pull requests of this repository.
I also found this bug a few weeks ago, the fix consists of "if __name__ == '__main__':".

**Comment by 4n4nk3** [comment]
Thank you for your feedback and your contribution.
I merged the [mentioned pull request](https://github.com/4n4nk3/Wordlister/pull/14) into the master branch.
